### ISSUE TITLE
error when lookup collection value is empty

### ISSUE THREAD

**Issue by konradsikorski** [konradsikorski/smartCAML#20]
The request failed.

System.InvalidOperationException: Sequence contains no elements

   at System.Linq.Enumerable.Aggregate[TSource](IEnumerable`1 source, Func`3 func)

   at KoS.Apps.SharePoint.SmartCAML.Providers.SharePoint2013ClientProvider.Converter.LookupCollectionValueToString(FieldLookupValue[] value)

   at KoS.Apps.SharePoint.SmartCAML.Providers.SharePoint2013ClientProvider.SharePoint2013ClientModelProvider.ElementSelector(Field field, ListItem item)

   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)

   at lambda_method(Closure , ListItem )

   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()

   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)

   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)

   at KoS.Apps.SharePoint.SmartCAML.Providers.SharePoint2013ClientProvider.SharePoint2013ClientModelProvider.<ExecuteQuery>d__13.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()

   at KoS.Apps.SharePoint.SmartCAML.Editor.MainWindow.<RunQueryCommand_Executed>d__11.MoveNext()

**Comment by konradsikorski** [comment]
done
